# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TennisPartner' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TennisPartner

  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'TennisPartnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TennisPartner-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TennisPartner-tvOS

  target 'TennisPartner-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
